#ifndef _CONSTANTS_H
#define _CONSTANTS_H



// PHYSICAL CONSTANTS SET USING ASTROPY VALUES
// but when using python, you should also use these values, due to round-off error
#define k_boltzmann 1.380649e-16
#define m_proton  1.672622e-24


// #define AU  1.495979e+13
#define pc_unit  3.085678e+18
#define M_sun 1.989100e+33
// #define R_sun  6.955080e+10

#define yr 3.155760e+07

#define kappa_0 6.1e-7



#endif	